version: '3.8'

services:
  sentiment_analysis:
    build: .
    volumes:
      - .:/app
      - ./output:/app/output
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
    env_file:
      - .env
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3